import os

S3_BUCKET_NAME = os.environ.get('S3_BUCKET_NAME')
S3_SAVE_INPUT_BUCKET = os.environ.get("S3_SAVE_INPUT_BUCKET")
REGION = os.environ.get("REGION")
SERVERLESS_DEPLOYMENT_BUCKET = os.environ.get("SERVERLESS_DEPLOYMENT_BUCKET")
PROJECT_NAME = os.environ.get("PROJECT_NAME")
STAGE = os.environ.get("STAGE")
SAGEMAKER_ENDPOINT = os.environ.get("SAGEMAKER_ENDPOINT")
S3_EMBEDDINGS_PATH = os.environ.get("S3_EMBEDDINGS_PATH")
print("S3_EMBEDDINGS_PATH config",S3_EMBEDDINGS_PATH)
EMBEDDINBGS_STAGE = os.environ.get("EMBEDDINBGS_STAGE")

